apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Provider
metadata:
  name: mock
spec:
  id: mock
  type: mock
  model: mock-model
  additional_config:
    mock_config: mock-responses.yaml
  defaults:
    temperature: 0.0
    max_tokens: 1500
    top_p: 1.0
